### ISSUE TITLE
Error when restarting after setting break point twice

### ISSUE THREAD

**Issue by RaisinTen** [nodejs/node-inspect#101]
```zsh
❯ node -v
v15.2.0
❯ npm -v
7.0.8
❯ cat test.js
process.stdin.resume();
❯ ./node_modules/node-inspect/cli.js test.js
< Debugger listening on ws://127.0.0.1:9229/da6a93a7-27a4-4eb0-9abd-da7bf4d7e812
< For help, see: https://nodejs.org/en/docs/inspector
< Debugger attached.
Break on start in test.js:1
> 1 process.stdin.resume();
  2 
debug> setBreakpoint(1)
> 1 process.stdin.resume();
  2 
debug> restart
< Debugger listening on ws://127.0.0.1:9229/bd969e56-b38e-4c0e-a202-e99cbc34dbd2
< For help, see: https://nodejs.org/en/docs/inspector
< Debugger attached.
Warning: script 'file:///home/raisinten/Desktop/universe/temp/project/report/report2/test.js' was not loaded yet.
1 breakpoints restored.
Break on start in test.js:1
> 1 process.stdin.resume();
  2 
debug> setBreakpoint(1)
> 1 process.stdin.resume();
  2 
debug> restart
< Debugger listening on ws://127.0.0.1:9229/3f518903-5194-437a-ac6d-5f68e9186f6e
< For help, see: https://nodejs.org/en/docs/inspector
< Debugger attached.
Warning: script 'file:///home/raisinten/Desktop/universe/temp/project/report/report2/test.js' was not loaded yet.
There was an internal error in node-inspect. Please report this bug.
Breakpoint at specified location already exists. - undefined
Error: Breakpoint at specified location already exists. - undefined
    at _pending.<computed> (/home/raisinten/Desktop/universe/temp/project/report/report2/node_modules/node-inspect/lib/internal/inspect_client.js:243:27)
    at Client._handleChunk (/home/raisinten/Desktop/universe/temp/project/report/report2/node_modules/node-inspect/lib/internal/inspect_client.js:213:11)
    at Socket.emit (node:events:329:20)
    at Socket.EventEmitter.emit (node:domain:529:15)
    at addChunk (node:internal/streams/readable:304:12)
    at readableAddChunk (node:internal/streams/readable:279:9)
    at Socket.Readable.push (node:internal/streams/readable:218:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:192:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:129:14)
```
I would expect it to not crash and work like the first iteration of `setBreakpoint + restart`.

**Comment by Trott** [comment]
I'm able to replicate this in Node.js 15. In Node.js 16, this still produces the "Breakpoint at specified location already exists." error but does not crash. That seems correct, or at least reasonable, to me. I'm going to close this, although I want to investigate what that "undefined" is all about after the error message.

**Comment by Trott** [comment]
Ah, I think it is a bug and I think I found what it is. Restoring the breakpoints on restart adds extra properties to the object stored to track breakpoints. Adding the breakpoint again and then restarting means that the same breakpoint gets restored twice because the extra properties means that the two different breakpoints in the array of known breakpoints don't match, so both get restored, but they're for the same location.

I'll get a fix in.

**Comment by Trott** [comment]
Looking more closely, this is a bug.

**Comment by Trott** [comment]
> Looking more closely, this is still a bug.

Specifically, the error should happen at the second `setBreakpoint()` and not after `restart()`.

**Comment by Trott** [comment]
I think is is a bug in the inspector code and not in the debugger/node-inspect code.
