### ISSUE TITLE
Not compatible with Nodejs version 5.12

### ISSUE THREAD

**Issue by Ralle** [nodejs/node-inspect#49]
I am running Node.js version 5.12 because it is the most recent version still supporting Windows Vista / Windows Server 2008 and I am getting the following error when trying to use node-inspect:

```
C:\Users\Rasmus\AppData\Roaming\npm\node_modules\node-inspect\lib\_inspect.js:23
const { spawn } = require('child_process');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Rasmus\AppData\Roaming\npm\node_modules\node-inspect\lib\cli.js:24:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

Is there something you can do?

**Comment by jkrems** [comment]
Hey @Ralle! Unfortunately `node-inspect` requires at least node 6 since it's designed to work against the new inspector protocol that didn't exist before node 6.

**Comment by Ralle** [comment]
Thanks for the response. Too bad. Anyway, I got around it by running a more recent Nodejs and using the built-in node --inspect but still distributing my product with 5.12.
