### ISSUE TITLE
node inspect crashes when tab-completing with a require

### ISSUE THREAD

**Issue by langdon-holly** [nodejs/node-inspect#64]
* **Version**: v11.1.0
* **Platform**: Linux setp 4.19.1-arch1-1-ARCH #1 SMP PREEMPT Sun Nov 4 16:49:26 UTC 2018 x86_64 GNU/Linux
* **Subsystem**:

Steps to reproduce:

0. Create an empty file named "test.js"
1. Run `node inspect test.js`
2. Enter the debug repl
3. Type `require("`
4. Press tab

Result: Node prints the following message to standard error, then exits with status 1.
```
There was an internal error in node-inspect. Please report this bug.
Cannot read property 'extensions' of undefined
TypeError: Cannot read property 'extensions' of undefined
    at REPLServer.complete (repl.js:1031:51)
    at REPLServer.completer (repl.js:492:14)
    at REPLServer.Interface._tabComplete (readline.js:476:8)
    at REPLServer.Interface._ttyWrite (readline.js:975:16)
    at REPLServer.self._ttyWrite (repl.js:719:7)
    at ReadStream.onkeypress (readline.js:178:10)
    at ReadStream.emit (events.js:182:13)
    at ReadStream.EventEmitter.emit (domain.js:441:20)
    at emitKeys (internal/readline.js:424:14)
    at emitKeys.next (<anonymous>)
```

Observed rules for reproduction:

* test.js can be any JavaScript file.
* A single quote may be substituted for the double quote in step 3.
* `require("` may be preceded by any JavaScript code.
* Space characters may be typed between `require` and `("`.
* The paren must be immediately followed by the quote (no whitespace).
* Any additional characters may be typed before pressing tab.
* The cursor must be somewhere after the quote when pressing tab.

**Comment by Trott** [comment]
> I think it would be best to transfer it to node-inspect since that is where it would need to be fixed.

Done!

**Comment by militello** [comment]
I had the same problem, the cause was using vm context:

**Comment by Trott** [comment]
I'm unable to reproduce this bug. @langdon-holly Are you still seeing this issue in Node.js 16.x or 14.x?

**Comment by langdon-holly** [comment]
@Trott I am unable to reproduce in v16.0.0.

**Comment by militello** [comment]
I was using 14.15.0

**Comment by militello** [comment]
This code is failing on 14.15.0 with the problem reported...

```js
const repl = require('repl');
const r = repl.start('teste> ');

const context = { x: 1, y: 2 };
r.context = require('vm').createContext(context);
```

It's the first time I create my own REPL so could be my mistake... 

But if the problem is just with the auto-complete, if it was catched we could still require (without auto-complete) and continue to use the REPL.

**Comment by militello** [comment]
Is there any better way to make a complex context from an object to use in REPL?

**Comment by Trott** [comment]
@langdon-holly I'm curious if this might be Linux distribution and/or processor specific. I just installed an Ubuntu docker image on macOS, then used `nvm` to install Node.js 11.1.0 and could not reproduce. (I thought maybe I had to use Linux to replicate, but apparently it would be more than just that.)

**Comment by langdon-holly** [comment]
I doubt it's processor-specific, but it could be OS-specific. I just tried node v11.1.0 on Arch Linux, again, and was able to reproduce. I also briefly looked at the source code, and it appears that the crash occurs at [repl.js:1031](https://github.com/nodejs/node/blob/v11.1.0/lib/repl.js#L1031) when completing a require, when the REPLServer's context has no 'require' property. Perhaps the OS or installation details affect the REPLServer's context?

**Comment by militello** [comment]
I'm running on ubuntu 20 here. Installed Node via [ASDF](https://github.com/asdf-vm/asdf).

**Comment by jkrems** [comment]
For the original bug (`require` combined with tab completion): There's something special about `require` in the context of the debugger. We inject a runtime API for `require` which allows it to work in the debug repl (or Chrome DevTools console) without a "real" global `require` when not stopped in a callstack frame with a `require` in scope.

The exception looks like the REPL code to auto-complete require paths blindly assumes that any `require` would have a `extensions` property - but the runtime API one doesn't have any properties. So maybe the answer here is to add defensive code to the REPL server code? See:

https://github.com/nodejs/node/blob/a03d3afa69451f32b74322858ece842132f67904/lib/repl.js#L1228

The require function in the command line API is set up here: https://github.com/nodejs/node/blob/a03d3afa69451f32b74322858ece842132f67904/lib/internal/util/inspector.js#L25-L37

**Comment by Trott** [comment]
@nodejs/repl
