### ISSUE TITLE
Internal error in node-inspect

### ISSUE THREAD

**Issue by jabberwock31415** [nodejs/node-inspect#86]
I got this error once.  It did not happen again.

There was an internal error in node-inspect. Please report this bug.
Payload does not look like JSON:
Error: Payload does not look like JSON:
    at Client._handleChunk (internal/deps/node-inspect/lib/internal/inspect_client.js:198:15)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:129:14)

* **Version**: v14.6.0
* **Platform**: Linux www 4.19.0-9-cloud-amd64 nodejs/node#1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
* **Subsystem**:

### What steps will reproduce the bug?

No idea--it happened once and not again when I ran "node inspect app.js"

**Comment by jkrems** [comment]
Thanks for the report! I think what @bnoordhuis wrote is the most likely explanation. Agreed that the error message could be better here!

**Comment by jabberwock31415** [comment]
I do call process.exit() in places in my code; this could definitely be the issue

**Comment by Trott** [comment]
Given that the code has moved to nodejs core (and a lot has changed) and that this has not recurred, I'm going to close this. However, if it recurs or if a reproduction is found, feel free to open an issue in http://github.com/nodejs/node.
